### ISSUE TITLE
L'utilisation de l'api sendBeacon() est bloquée par uBlock Origin

### ISSUE THREAD

**Issue by Herve07h22** [Herve07h22/fairlytics-community#10]
Lorsqu'un visiteur a installé l'extension `uBlock Origin` sur son navigateur, sa visite n'est pas comptabilisée.
Le plug bloque toutes les requêtes émises via l'API sendBeacon.

Il faut donc modifier le script `tag.js` afin de remplacer l'appel `navigator.sendBeacon("https://app.fairlytics.tech/hit", JSON.stringify(payload));` par un appel avec `XMLHttpRequest`.

**Comment by Phil353556** [comment]
Bonjour, Effectivement, je viens de tester/vérifier 
![image](https://github.com/Herve07h22/fairlytics-community/assets/64729485/e2bee9b0-a576-4ab6-9984-2062ae92fc14)

Mais XMLHttpRequest semble déprécié depuis quelques années ... comment faire ?
 https://stackoverflow.com/questions/41008093/xmlhttprequest-is-deprecated-what-to-use-instead
 Cdlt

**Comment by Herve07h22** [comment]
C'est la partie synchrone qui est dépréciée. 

Mais ça convient parfaitement pour ce qu'on souhaite faire.
Traité par le commit [4eab7066827fd60f3823b38254eedbc862e8aff9](https://github.com/Herve07h22/fairlytics-community/commit/4eab7066827fd60f3823b38254eedbc862e8aff9)
